export const FETCH_MY_LIST_MOVIES_START = "FETCH_MY_LIST_MOVIES_START";
export const FETCH_MY_LIST_MOVIES_SUCCESS = "FETCH_MY_LIST_MOVIES_SUCCESS";
export const FETCH_MY_LIST_MOVIES_ERROR = "FETCH_MY_LIST_MOVIES_ERROR";

export const ADD_TO_MY_LIST_MOVIES_START = "ADD_TO_MY_LIST_MOVIES_START";
export const ADD_TO_MY_LIST_MOVIES_SUCCESS = "ADD_TO_MY_LIST_MOVIES_SUCCESS";
export const ADD_TO_MY_LIST_MOVIES_ERROR = "ADD_TO_MY_LIST_MOVIES_ERROR";

export const REMOVE_FROM_MY_LIST_MOVIES_START =
	"REMOVE_FROM_MY_LIST_MOVIES_START";
export const REMOVE_FROM_MY_LIST_MOVIES_SUCCESS =
	"REMOVE_FROM_MY_LIST_MOVIES_SUCCESS";
export const REMOVE_FROM_MY_LIST_MOVIES_ERROR =
	"REMOVE_FROM_MY_LIST_MOVIES_ERROR";
